name: Extract and Overwrite
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract_zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract ZIP and overwrite
        run: |
          unzip -o full.zip -d .

      - name: Commit and push changes
        run: |
          git commit -m "Automated unzip and overwrite" || echo "No changes to commit"
          git push
